server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: member-service
  # config service settings
  kafka:
    consumer:
      group-id: test
  cloud:
    config:
      name: member-service
  jackson:
    time-zone: Asia/Seoul
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh